led_dashboard/urls.py
from django.urls import path, include

urlpatterns = [
	path('', include('main.urls')),
	# path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
	path('', views.RootPageView.as_view(), name='root'),
	path('control/', views.StripControlFormSubmit.as_view(), name='strip-control'),
	path('set-profile/', views.ProfileSelectFormSubmit.as_view(), name='set-profile'),
]

main/models.py
from django.core import validators
from django.db import models


class SingletonModel(models.Model):
	"""https://steelkiwi.com/blog/practical-application-singleton-design-pattern/"""
	class Meta:
		abstract = True

	def save(self, *args, **kwargs):
		self.pk = 1
		super(SingletonModel, self).save(*args, **kwargs)

	def delete(self, *args, **kwargs):
		pass

	@classmethod
	def load(cls):
		obj, created = cls.objects.get_or_create(pk=1)
		return obj


class LightStrip(SingletonModel):
	power = models.BooleanField("light strip power", default=True)
	brightness = models.IntegerField(
		"brightness level",
		validators=[validators.MinValueValidator(0), validators.MaxValueValidator(255)],
		default=128)
	current_profile = models.CharField("currently selected profile", max_length=256, blank=True, null=True, default=None)

	@classmethod
	def primary_strip(cls):
		"""There's probably, very likely, almost certainly, going to be just a single strip to manage."""
		return LightStrip.load()

main/forms.py
from django import forms


class StripControlForm(forms.Form):
	power = forms.BooleanField(label="Power", initial=True, required=False)
	brightness = forms.IntegerField(label="Brightness", initial=128, required=False)
	reset = forms.BooleanField(label="Reset", initial=False, required=False, widget=forms.HiddenInput())

	def __init__(self, power=None, brightness=None, **kwargs):
		super(StripControlForm, self).__init__(**kwargs)
		if power is not None:
			self.fields['power'].initial = power
		if brightness is not None:
			self.fields['brightness'].initial = brightness


class ProfileSelectForm(forms.Form):
	profile = forms.CharField(label="Profile", widget=forms.HiddenInput())

	def __init__(self, profile_name=None, **kwargs):
		super(ProfileSelectForm, self).__init__(**kwargs)
		self.fields['profile'].initial = profile_name

main/views.py
import logging

from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView

from main import rgbd
from main.forms import StripControlForm, ProfileSelectForm
from main.models import LightStrip

log = logging.getLogger(__name__)


class RootPageView(TemplateView):
	template_name = 'main/root.html'

	def get_context_data(self, **kwargs):
		context = super(RootPageView, self).get_context_data(**kwargs)

		light_strip = LightStrip.primary_strip()
		context['light_strip'] = light_strip

		control_form = StripControlForm(power=light_strip.power, brightness=light_strip.brightness)
		context['control_form'] = control_form

		strip_profiles = rgbd.find_profiles()
		for profile in strip_profiles:
			profile.form = ProfileSelectForm(profile_name=profile.name)
		context['strip_profiles'] = strip_profiles

		return context


# TODO: Combine these into a single endpoint that can handle everything

class StripControlFormSubmit(View):

	def post(self, request):
		print("Strip control submit: {}".format(request.POST))
		form = StripControlForm(data=request.POST)
		if form.is_valid():
			light_strip = LightStrip.primary_strip()
			if form.cleaned_data['reset']:
				default_strip = LightStrip()
				light_strip.power = default_strip.power
				light_strip.brightness = default_strip.brightness
			else:
				light_strip.power = form.cleaned_data['power']
				light_strip.brightness = form.cleaned_data['brightness']
			# Apply the settings before saving, if there is an error the changes won't commit
			rgbd.set_brightness(light_strip.brightness if light_strip.power else 0)
			light_strip.save()
			return HttpResponseRedirect(reverse('main:root'))
		else:
			return HttpResponseBadRequest()


class ProfileSelectFormSubmit(View):

	def post(self, request):
		print("Profile select submit: {}".format(request.POST))
		form = ProfileSelectForm(data=request.POST)
		if form.is_valid():
			light_strip = LightStrip.primary_strip()
			light_strip.current_profile = form.cleaned_data['profile']
			# Apply the settings before saving, if there is an error the changes won't commit
			try:
				rgbd.switch_to_profile(rgbd.lookup_profile(light_strip.current_profile))
				light_strip.save()
				rgbd.set_brightness(light_strip.brightness if light_strip.power else 0)
			except ValueError as ex:
				log.warning("Unable to switch profiles: {}".format(str(ex)))
			return HttpResponseRedirect(reverse('main:root'))
		else:
			return HttpResponseBadRequest()

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Lights Dashboard</title>

		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="stylesheet" href="{% static 'main/bootstrap-4.3.1/bootstrap-theme-cyborg.min.css' %}">
		<link rel="stylesheet" href="{% static 'main/input-slider-theme-dark.css' %}">
		<style>
			hr { border-color: #888888; }
		</style>
	</head>
	<body>
		{% block content %}
		{% endblock content %}

		<script src="{% static 'main/jquery-3.4.0-slim/jquery-3.4.0.slim.min.js' %}"></script>
		<script src="{% static 'main/bootstrap-4.3.1/bootstrap.bundle.min.js' %}"></script>
	</body>
</html>

main/templates/main/root.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container">

	<h1>Lights Dashboard</h1>
	<hr>

	<h2>Strip Control</h2>
	<form action="{% url 'main:strip-control' %}" method="POST">
		{{ control_form.non_field_errors }}

		<fieldset class="form-group">
			{{ control_form.power.errors }}
			<legend>{{ control_form.power.label }}</legend>
			<div class="btn-group btn-group-toggle btn-block" data-toggle="buttons">
				<label class="btn btn-outline-success {% if control_form.power.value %} active {% endif %}">
					<input type="radio" name="power" id="power_on" value="true"
					       {% if control_form.power.value %} checked {% endif %}> On
				</label>
				<label class="btn btn-outline-danger {% if not control_form.power.value %} active {% endif %}">
					<input type="radio" name="power" id="power_off" value="false"
					       {% if not control_form.power.value %} checked {% endif %}> Off
				</label>
			</div>
		</fieldset>

		<fieldset class="form-group">
			{{ control_form.brightness.errors }}
			<legend>{{ control_form.brightness.label }}</legend>
			<div class="form-row align-items-center">
				<div class="col-9">
					<input type="range" name="brightness" id="brightness_slide" class="form-control-range"
					       min="0" max="255" value="{{ control_form.brightness.value }}"
					       onchange="brightness_num.value=value">
				</div>
				<div class="col-3">
					<input type="number" id="brightness_num" class="form-control"
					       min="0" max="255" value="{{ control_form.brightness.value }}"
					       onchange="brightness_slide.value=value">
				</div>
			</div>
		</fieldset>

		<div class="container my-4">
			<div class="row">
				<button type="submit" class="col btn btn-primary">Update Strip</button>
				<button type="submit" class="col-3 col-md-2 ml-2 btn btn-danger" name="reset" value="true">Reset</button>
			</div>
		</div>
	</form>

	<hr>

	<h2>Profile Select</h2>
	{% for profile in strip_profiles %}
	<form action="{% url 'main:set-profile' %}" method="POST">
		<div class="d-flex flex-row align-items-center mb-2">
			<span class="m-1"><b>{{ profile.name }}</b></span>
			{% if profile.name == light_strip.current_profile %}
			<span class="m-1 text-success"><i>Current profile</i></span>
			{% endif %}
			{{ profile.form.profile }}
			<button type="submit" class="ml-auto btn btn-outline-primary">Switch To</button>
		</div>
	</form>
	{% empty %}
	<p>
		No profiles available :( <br>This is probably an error. Check the server log!
	</p>
	{% endfor %}

</div>

{% endblock content %}